os: linux
dist: trusty
language: cpp
compiler:
  - clang
  - gcc
cache: ccache

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - ccache
    - cmake

script:
  # Output version info for compilers, cmake, and make
  - ${CC} -v
  - ${CXX} -v
  - cmake --version
  - make --version
  # Configure and build
  - mkdir _travis_build && cd _travis_build
  - cmake -G "Unix Makefiles" -DENABLE_TESTS=ON -DENABLE_CCACHE=ON ..
  - make -j
  - ./draco_tests
