os: linux
dist: trusty
language: cpp
compiler:
  - clang
  - gcc
cache: ccache

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - ccache
    - cmake

script:
  # Output versions of gcc, g++ and cmake
  - clang -v
  - clang++ -v
  - gcc -v
  - g++ -v
  - make --version
  # Configure and build
  - mkdir _travis_build && cd _travis_build
  - cmake -G "Unix Makefiles" -DENABLE_TESTING=ON -DENABLE_CCACHE=ON ..
  - make -j
  - ./draco_tests
